name: UFLx CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-26.04
    steps:
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
      - uses: actions/checkout@v7
      - name: Ruff check
        run: |
          pip install ruff
          ruff check .
          ruff format --check .
      - name: Install UFLx
        run: pip install -e ".[lint,ci]"
      - name: Install external libraries
        run: |
          pip install external/codegeneration
          pip install external/basix_uflx
      - name: Pyrefly check
        run: pyrefly check

  build:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-26.04]
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UFLx
        run: pip -v install .[ci,docs]
      - name: Run units tests
        run: pytest -n auto --durations 20 test/

      - name: Check test coverage is high
        run: |
          pip -v install pytest-cov
          pytest -n auto --cov-report json:.coverage.json --cov-report term --cov=uflx --durations 20 test/
          python3 .github/scripts/coverage_check.py

      - name: Install external libraries
        run: |
          pip -v install external/codegeneration
          pip -v install external/basix_uflx
      - name: Run units tests
        run: pytest -n auto --durations 20 external/*/test/

      - name: Build doc
        working-directory: ./doc
        run: make html

  coverage:
    name: Check test coverage
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-26.04]
        python-version: ["3.14"]
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install UFLx and pytest-cov
        run: |
          pip -v install -e .[ci,docs]
          pip -v install pytest-cov

      - name: Run tests
        run: pytest -n auto --cov-report json:.coverage.json --cov-report term --cov=uflx --durations 20 test/
      - name: Check test coverage is high
        run: python3 .github/scripts/coverage_check.py
